---
title: America by Rail and Bus Travel Blog
author: Elle G
email: mydigitalpicasso@yahoo.com
description: Travel tips for foreign visitors and Americans travelling the USA by
  bus and train
baseurl: "/"
url: ''
defaults:
- scope: ''
  values: ''
plugins:
- jekyll-feed
- jekyll-menus
