---
title: America by Rail and Bus Travel Blog
author: Elle G
email: mydigitalpicasso@yahoo.com
description: Travel tips for foreign visitors and Americans travelling the USA by
  bus and train
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope: ''
  values: ''
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
